config/routes.rb
# frozen_string_literal: true
require "sidekiq/web"

Rails.application.routes.draw do
  namespace :admin do
    get "/auth/google_oauth2/callback" => "sessions#create"
    get "/auth/failure", to: redirect("/401", 302)

    get "/login", to: redirect("/admin/auth/google_oauth2", 302)
    get "/logout" => "sessions#destroy"

    constraints AdminConstraint.new do
      mount Sidekiq::Web, at: "/sidekiq"

      root to: redirect("/admin/sidekiq", 302)
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :academic_degree_terms, only: [] do
    resources :agendas, except: :show, param: :token, shallow: true do
      get "/", to: redirect("/agendas/%{agenda_token}/schedules", 302)

      resources :schedules, only: :index, constraints: ->(r) { r.params.fetch(:page, "1") =~ /^[1-9]\d*$/ } do
        get :processing, on: :collection
      end
    end
  end

  resources :agendas, param: :token, only: [] do
    resources :schedules, only: :show, param: :index, constraints: { index: /[1-9]\d*/ }
  end

  resources :comments, only: [:new, :create]

  resource :faq, only: :show

  resources :terms, only: :index do
    collection do
      post :create_newsletter_subscription
    end
  end

  ErrorsController::MAPPED_ERRORS.each do |status, code|
    get "/#{code}", to: "errors##{status}", as: status
  end

  root "terms#index"
end

app/models/term.rb
# frozen_string_literal: true
class Term < ApplicationRecord
  has_many :academic_degree_terms,
           -> { joins(:academic_degree).order("academic_degrees.name DESC") },
           dependent: :delete_all
  has_many :academic_degrees, through: :academic_degree_terms

  validates :year, presence: true
  validates :name, presence: true, uniqueness: { scope: [:year, :tags] }

  scope :enabled, -> { where("enabled_at IS NOT NULL").order(year: :desc, name: :asc, tags: :asc) }
end

app/controllers/terms_controller.rb
# frozen_string_literal: true
class TermsController < ApplicationController
  before_action :assign_terms

  def index
    @newsletter_subscription = NewsletterSubscription.new
  end

  def create_newsletter_subscription
    @newsletter_subscription = NewsletterSubscription.new(newsletter_subscription_params)

    if @newsletter_subscription.save
      redirect_to root_path, flash: { notice: t(".success") }
    else
      render :index
    end
  end

  private

  def assign_terms
    @terms = Term.includes(:academic_degree_terms, academic_degree_terms: :academic_degree).enabled.all
  end

  def newsletter_subscription_params
    params.require(:newsletter_subscription).permit(:email)
  end
end

app/helpers/terms_helper.rb
# frozen_string_literal: true
module TermsHelper
  def term_title(term)
    [term.name, term.year, term_tags(term)].compact.join(" ")
  end

  private

  def term_tags(term)
    "- #{term.tags}" if term.tags.present?
  end
end

app/views/terms/_term.html.haml
.col-sm-6.col-xs-12
  .panel.panel-default
    .panel-heading
      .panel-title= term_title(term)

    .list-group
      - term.academic_degree_terms.each do |academic_degree_term|
        = link_to academic_degree_term.name, new_academic_degree_term_agenda_path(academic_degree_term),
          class: "list-group-item"

app/views/terms/index.html.haml
.hero-jumbotron
  .container
    %h1= t(".title")
    %p= t(".subtitle")

= form_for @newsletter_subscription, url: create_newsletter_subscription_terms_path,
  html: { class: "form-horizontal" } do |f|
  .container
    = render "shared/google_adsense"
    = render "shared/flash_messages"

    %p
      = link_to "#newsletter-subscription-collapse", data: { toggle: "collapse" } do
        %i.fa.fa-bell-o
        = t(".newsletter_subscription_message")

  .collapse#newsletter-subscription-collapse{ class: ("in" if f.object.errors.present?) }
    .well
      .container
        .form-group{ class: ("has-error" if f.object.errors.key?(:email)) }
          = f.label :email, class: "col-sm-1 control-label"
          .col-sm-11
            = f.text_field :email, class: "form-control"
            - f.object.errors[:email].each do |error|
              .help-block= error

        = f.submit class: "col-xs-12 col-sm-4 pull-right btn btn-primary btn-sm"

.container
  - @terms.each_slice(2) do |terms_slice|
    .row= render partial: "term", collection: terms_slice