config/routes.rb
# frozen_string_literal: true
require "sidekiq/web"

Rails.application.routes.draw do
  namespace :admin do
    get "/auth/google_oauth2/callback" => "sessions#create"
    get "/auth/failure", to: redirect("/401", 302)

    get "/login", to: redirect("/admin/auth/google_oauth2", 302)
    get "/logout" => "sessions#destroy"

    constraints AdminConstraint.new do
      mount Sidekiq::Web, at: "/sidekiq"

      root to: redirect("/admin/sidekiq", 302)
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :academic_degree_terms, only: [] do
    resources :agendas, except: :show, param: :token, shallow: true do
      get "/", to: redirect("/agendas/%{agenda_token}/schedules", 302)

      resources :schedules, only: :index, constraints: ->(r) { r.params.fetch(:page, "1") =~ /^[1-9]\d*$/ } do
        get :processing, on: :collection
      end
    end
  end

  resources :agendas, param: :token, only: [] do
    resources :schedules, only: :show, param: :index, constraints: { index: /[1-9]\d*/ }
  end

  resources :comments, only: [:new, :create]

  resource :faq, only: :show

  resources :terms, only: :index do
    collection do
      post :create_newsletter_subscription
    end
  end

  ErrorsController::MAPPED_ERRORS.each do |status, code|
    get "/#{code}", to: "errors##{status}", as: status
  end

  root "terms#index"
end

app/models/agenda.rb
# frozen_string_literal: true
class Agenda < ApplicationRecord
  include Defaults
  include SerializedRecord::AcceptsNestedAttributeFor

  COURSES_PER_SCHEDULE_RANGE = 1..5

  belongs_to :academic_degree_term
  has_one :academic_degree, through: :academic_degree_term
  has_one :term, through: :academic_degree_term
  has_many :academic_degree_term_courses, through: :academic_degree_term
  has_many :courses, autosave: true, dependent: :delete_all, inverse_of: :agenda
  has_many :schedules, dependent: :delete_all

  accepts_nested_attributes_for :courses, allow_destroy: true

  serialize :leaves, LeavesSerializer
  serialized_accepts_nested_attributes_for :leaves

  validates :courses, presence: true
  validates :courses_per_schedule, inclusion: { in: Agenda::COURSES_PER_SCHEDULE_RANGE }
  validates_with Validator

  default :courses_per_schedule, COURSES_PER_SCHEDULE_RANGE.begin
  default :processing, false
  default(:token) { SecureRandom.hex }

  delegate :count, to: :schedules, prefix: true
  delegate :name, to: :academic_degree, prefix: true

  alias_attribute :to_param, :token

  def mark_as_finished_processing
    self.processing = false
    self.combined_at = Time.zone.now
  end
end

app/models/agenda/course.rb
# frozen_string_literal: true
class Agenda::Course < ApplicationRecord
  include Defaults

  delegate :code, to: :academic_degree_term_course

  belongs_to :academic_degree_term_course
  belongs_to :agenda, inverse_of: :courses, touch: true

  serialize :group_numbers, JSON

  validates :academic_degree_term_course, presence: true
  validates :selected_groups, presence: true

  scope :mandatory, -> { where(mandatory: true) }
  scope :optional, -> { where(mandatory: false) }

  default :group_numbers, []
  default :mandatory, false

  def academic_degree_term_course_groups
    academic_degree_term_course&.groups || []
  end

  def group_numbers=(value)
    super value.select(&:present?).map(&:to_i)
  end

  def pruned_groups
    selected_groups.reject(&method(:overlaps_leaves?))
  end

  def reset_group_numbers
    self.group_numbers = academic_degree_term_course.group_numbers
  end

  private

  def selected_groups
    academic_degree_term_course_groups.select { |group| group.number.in?(group_numbers) }
  end

  def overlaps_leaves?(group)
    agenda.leaves.any? do |leave|
      group.periods.any? { |period| leave.overlaps?(period) }
    end
  end
end

app/models/agenda/validator.rb
# frozen_string_literal: true
class Agenda::Validator < ActiveModel::Validator
  def validate(agenda)
    MemoizedValidator.new(agenda).execute
  end

  class MemoizedValidator < SimpleDelegator
    include MemoizedCourseScopes

    def execute
      courses.each(&:validate)
      validate_courses
      validate_leaves
    end

    def validate_courses
      if courses.empty?
        errors.add(:courses, :blank)
      elsif courses_mismatch?
        errors.add(:courses, :greater_than_or_equal_to_courses_per_schedule)
      elsif mandatory_courses_overflow?
        errors.add(:courses, :mandatory_courses_less_than_or_equal_to_courses_per_schedule)
      elsif mandatory_courses_redundant?
        errors.add(:courses, :mandatory_courses_redundant)
      end
    end

    def validate_leaves
      errors.add(:leaves, :invalid) if leaves.map(&:invalid?).any?
    end

    def courses_mismatch?
      courses_per_schedule.present? && courses.size < courses_per_schedule
    end

    def mandatory_courses_overflow?
      courses_per_schedule.present? && mandatory_courses.size > courses_per_schedule
    end

    def mandatory_courses_redundant?
      mandatory_courses.size == courses_per_schedule && optional_courses.present?
    end

    def courses
      @courses ||= super.reject(&:marked_for_destruction?)
    end
  end
end

app/controllers/agendas_controller.rb
# frozen_string_literal: true
class AgendasController < ApplicationController
  include AgendaEagerLoading
  include BrowserCaching

  before_action :invalidate_browser_cache
  before_action :assign_academic_degree_term,
                :instantiate_agenda, only: [:new, :create]
  before_action :find_agenda,
                :ensure_not_processing, only: [:edit, :update]
  before_action :eager_load_courses
  before_action :assign_attributes, only: [:create, :update]
  before_action :save, only: [:create, :update]

  delegate :step, to: :agenda_creation_process
  helper_method :step

  def new
    render step
  end

  def edit
    render step
  end

  def create; end

  def update; end

  private

  def assign_academic_degree_term
    @academic_degree_term = AcademicDegreeTerm.enabled.find(params[:academic_degree_term_id])
  end

  def instantiate_agenda
    @agenda = @academic_degree_term.agendas.new
  end

  def agenda_params
    params.require(:agenda).permit(
      :courses_per_schedule,
      :filter_groups,
      courses_attributes: [:_destroy, :academic_degree_term_course_id, :id, :mandatory, { group_numbers: [] }],
      leaves_attributes: [:_destroy, :ends_at, :starts_at]
    )
  end

  def agenda_token
    params.require(:token)
  end

  def assign_attributes
    @agenda.assign_attributes(agenda_params)
  end

  def agenda_creation_process
    @agenda_creation_process ||= AgendaCreationProcess.new(agenda: @agenda, step: params[:step])
  end

  def save
    agenda_creation_process.save ? redirect_to(agenda_creation_process.path) : render(step)
  end

  def ensure_not_processing
    redirect_to(processing_agenda_schedules_path(@agenda)) if @agenda.processing?
  end
end

app/views/agendas/_leave.html.haml
.leave.row{ class: ("has-error" if f.object.errors.any?) }
  - if f.object.errors.any?
    .col-xs-12
      - f.object.errors.each do |_, error|
        .help-block= error
  .col-sm-5
    .form-group
      = f.label :starts_at, class: "col-sm-2 control-label"
      .col-sm-10
        = f.collection_select :starts_at,
                              leave_times,
                              :total_minutes,
                              ->(leave) { week_time_format(leave) },
                              {},
                              class: "form-control",
                              data: { "leave-starts-at" => f.index }
  .col-sm-5
    .form-group
      = f.label :ends_at, class: "col-sm-2 control-label"
      .col-sm-10
        = f.collection_select :ends_at,
                              leave_times,
                              :total_minutes,
                              ->(leave) { week_time_format(leave) },
                              {},
                              class: "form-control",
                              data: { "leave-ends-at" => f.index }
  .col-xs-4.col-sm-2.pull-right
    = f.destroy_button "-", class: "btn btn-default btn-block"

app/views/agendas/course_selection.html.haml
.container
  = render "shared/breadcrumb"
  = render "shared/flash_messages"

  - if @agenda.errors.any?
    .alert.alert-danger{ role: "alert" }
      - @agenda.errors.each do |_, error|
        %span.glyphicon.glyphicon-exclamation-sign{ "aria-hidden" => true }
        = error
        %br

  %h1.page-header= t(".title")

= form_for [@academic_degree_term, @agenda] do |f|
  = hidden_field_tag :step, step
  = render "shared/overview", f: f

  .container
    %fieldset
      %legend= f.label :courses
      %p= t(".mandatory_courses_explication_html")

      - @agenda.academic_degree_term_courses.each_with_index do |academic_degree_term_course, index|
        :ruby
          agenda_course = @agenda.courses.find do |course|
            course.academic_degree_term_course == academic_degree_term_course
          end

        .course-checkbox-button.btn-group.btn-group-justified{ role: "group" }
          - unless agenda_course.nil?
            = hidden_field_tag "agenda[courses_attributes][#{index}][id]", agenda_course.id, id: nil
          = hidden_field_tag "agenda[courses_attributes][#{index}][academic_degree_term_course_id]",
            academic_degree_term_course.id, id: nil
          = hidden_field_tag "agenda[courses_attributes][#{index}][mandatory]", false, id: nil
          = hidden_field_tag "agenda[courses_attributes][#{index}][_destroy]", true, id: nil

          = check_box_tag "agenda[courses_attributes][#{index}][_destroy]", false, agenda_course.present?,
            data: { "child-checkbox" => "agenda_courses_attributes_#{index}_mandatory" }
          = label_tag "agenda_courses_attributes_#{index}__destroy", class: "btn btn-default" do
            = academic_degree_term_course.code

          = check_box_tag "agenda[courses_attributes][#{index}][mandatory]", true, agenda_course&.mandatory?
          = label_tag "agenda_courses_attributes_#{index}_mandatory", class: "btn btn-default" do
            %i.checked.fa.fa-lock
            %i.unchecked.fa.fa-unlock-alt

    .checkbox
      = f.label :filter_groups do
        = f.check_box :filter_groups
        = t(".filter_groups")

    %fieldset
      %legend= f.label :courses_per_schedule
      .btn-group.courses-per-schedule-group.btn-group-justified
        = f.collection_radio_buttons :courses_per_schedule, Agenda::COURSES_PER_SCHEDULE_RANGE, :to_i, :to_i do |ff|
          = ff.radio_button
          = ff.label(class: "btn btn-default")

    %a.schedules-anchor{ name: "leaves" }
    %fieldset.form-horizontal
      %legend= f.label :leaves
      = f.nested_form :leaves
      = f.create_button :leaves, "+", class: "btn btn-default col-xs-12 col-sm-4 pull-right"

    = f.submit class: "col-xs-12 col-sm-4 pull-right btn btn-primary"

app/views/agendas/group_selection.html.haml
.container
  = render "shared/breadcrumb"
  = render "shared/flash_messages"

  - if @agenda.errors.any?
    .alert.alert-danger{ role: "alert" }
      - @agenda.errors.each do |_, error|
        %span.glyphicon.glyphicon-exclamation-sign{ "aria-hidden" => true }
        = error
        %br

  %h1.page-header= t(".title")

= form_for [@academic_degree_term, @agenda] do |agenda_fields|
  = hidden_field_tag :step, step
  = render "shared/overview", f: agenda_fields

  .container
    %fieldset
      %legend= t(".groups")

      = agenda_fields.fields_for :courses do |course_fields|
        %table.group-selection-table
          %thead
            %tr{ class: ("danger" if course_fields.object.errors.any?) }
              %th{ colspan: 3 }
                = course_fields.hidden_field :id
                = course_fields.object.code
                |
                - if course_fields.object.mandatory?
                  %i.fa.fa-lock
                - else
                  %i.fa.fa-unlock

          %tbody
            - group_index = 0
            = course_fields.collection_check_boxes :group_numbers,
              course_fields.object.academic_degree_term_course_groups, :number, :number do |group_fields|
              - group_index += 1
              - group_fields.object.periods.each_with_index do |period, index|
                %tr{ class: ("active" if group_index.odd?) }
                  - if index.zero?
                    %th{ rowspan: group_fields.object.periods.size }
                      = group_fields.label do
                        .label-content
                          = group_fields.check_box
                          = group_fields.text
                  %td
                    = group_fields.label do
                      .label-content
                        = period.type
                  %td
                    = group_fields.label do
                      .label-content
                        = period_time_span(period)

    .row
      .col-sm-4.col-sm-push-8
        = agenda_fields.submit class: "btn btn-primary btn-block"
      .col-sm-8.col-sm-pull-4.back
        = link_to edit_agenda_path(@agenda, step: :course_selection) do
          %i.glyphicon.glyphicon-chevron-left
          = t(".back")